development:
  cloud_name: <%= ENV.fetch("CLOUDINARY_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_SECRET") %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV.fetch("CLOUDINARY_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_SECRET") %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= ENV.fetch("CLOUDINARY_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_SECRET") %>
  enhance_image_tag: true
  static_file_support: false