default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onebittweet_api_development
  username: postgres
  password:

test:
  <<: *default
  database: onebittweet_api_test
  username: postgres
  password:

production:
  <<: *default
  database: onebittweet_api_production
  username: onebittweet_api
  password: <%= ENV['ONEBITTWEET_API_DATABASE_PASSWORD'] %>
